# -*- coding: utf-8 -*-

DEBUG = True
SQLALCHEMY_TRACK_MODIFICATIONS = True
CSRF_ENABLED = True
SECRET_KEY = 'asdfghjkl'
SQLALCHEMY_POOL_SIZE = 100
SQLALCHEMY_POOL_RECYCLE = 10
SQLALCHEMY_POOL_TIMEOUT = 3000
SQLALCHEMY_DATABASE_URI = 'mysql://user:passwd@127.0.0.1:3306/laas'